name: Deploy
on:
  push:
    branches:
      - "!*"
    tags:
      - '*'
jobs:
  job-1:
    name: Assets
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        run: git clone https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git .
      - name: Checkout tag
        run: git checkout $(echo ${{ github.ref }} | cut -d / -f 3)
      - name: Composer install
        run: composer install --no-dev -o
      - name: Compile Phar
        run: php --define phar.readonly=0 .github/workflows/phar/compile.php
      - name: Upload phar
        run: php .github/workflows/phar/upload.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
